package network.backend

import error.ServerResponseException
import network.backend.model.BackendConnector
import request.LoginRequest
import response.endpoint.LoginResult
import server.Endpoints

object Authentication : BackendConnector() {
    /**
     * Tries to log in with the given credentials. Failures are thrown.
     *
     * @param nif The NIF of the user to authenticate.
     * @param password The password of the given user.
     *
     * @return If login is successful, the JWT token generated by the server.
     *
     * @throws ServerResponseException If the login could not be completed.
     */
    suspend fun login(nif: String, password: String): String {
        val result = post<LoginResult>(Endpoints.Authenticate.Login, body = LoginRequest(nif, password))
        return result.token
    }
}
