name: Run tests

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      server: ${{ steps.filter.outputs.server }}
      app: ${{ steps.filter.outputs.app }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            server:
              - 'server/**'
              - 'shared/**'
              - '*.gradle.kts'
              - 'gradle.properties'
              - 'gradle/**'
              - '.github/workflows/test.yml'
            app:
              - 'composeApp/**'
              - 'shared/**'
              - '*.gradle.kts'
              - 'gradle.properties'
              - 'gradle/**'
              - '.github/workflows/test.yml'

  test-server:
    name: Run Server tests
    runs-on: ubuntu-latest

    needs: changes
    if:  ${{ needs.changes.outputs.server == 'true' }}

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@342dbebe7272035434f9baccc29a816ec6dd2c7b
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6
        env:
          ENV_TEST_VAR_STR: testing
          ENV_TEST_VAR_INT: 123456
          ENV_TEST_VAR_FLO: 123.456
          ENV_TEST_VAR_BOO: true
          ENV_TEST_VAR_ENUM: TEST2
        with:
          arguments: :server:check
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Server Reports
          path: |
            server/build/reports/
            server/build/test-results/

  test-app:
    name: Run App tests
    runs-on: ubuntu-latest

    needs: changes
    if:  ${{ needs.changes.outputs.app == 'true' }}

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@342dbebe7272035434f9baccc29a816ec6dd2c7b
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6
        with:
          arguments: :composeApp:check
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: App Reports
          path: |
            composeApp/build/reports/
            composeApp/build/test-results/
